name: build-openapi

on:
  workflow_dispatch:
    
jobs:
  build-openapi-doc:
    runs-on: ubuntu-latest
    env:
      MAJOR_VERSION: 9
      MINOR_VERSION: 0
      SOLUTION_PATH: ./src/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x    
        
      - name: Restore dependencies
        run: dotnet restore $SOLUTION_PATH
      
      - name: Build
        run: dotnet build $SOLUTION_PATH --no-restore --ignore-failed-sources -c Release
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OPENAPI-JSON
          path: ./src/Rocket.Api.Host/openapi/Rocket.Api.Host.json
          if-no-files-found: error
          include-hidden-files: true
          
  update-openapi-doc:
    name: Update OpenAPI Documentation
    needs: build-openapi-doc
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: OPENAPI-JSON
          path: ./artifact
          
      - name: Update version tag
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "Version: $VERSION"
          sed -i "s/##{VERSION_TAG}##/$VERSION/g" ./artifact/Rocket.Api.Host.json
          cat ./artifact/Rocket.Api.Host.json | grep -A2 -B2 "version"
          
      - name: Clone documentation repository
        run: |
          git clone https://x-access-token:${{ secrets.BOTTLE_ROCKET_REPO_PAT }}@github.com/gman-au/bottle-rocket-documentation.git api-docs
          
      - name: Update documentation and push
        run: |
          cd api-docs
          git config user.name "Rocket-Bot"
          git config user.email "info@gman.com.au"
          
          BRANCH_NAME="api-version-${{ github.sha }}"
          git checkout -b "$BRANCH_NAME"
          
          # Ensure target directory exists
          mkdir -p ./api-static/src/openapi/
          
          # Copy the updated JSON file
          cp ../artifact/Rocket.Api.Host.json ./api-static/src/openapi/Rocket.Api.Host.json
          
          git add .
          
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected. Committing and pushing."
            git commit -m "doc: Updated API document to version ${{ github.ref_name }}"
            git push --set-upstream origin "$BRANCH_NAME"
            echo "Branch $BRANCH_NAME pushed successfully"
          else
            echo "No changes to commit."
          fi
          
      - name: Create Pull Request
        run: |
          cd api-docs
          gh pr create \
            --title "Update API documentation to ${{ github.ref_name }}" \
            --body "Automated update of OpenAPI specification" \
            --base main \
            --head "api-version-${{ github.sha }}"
        env:
          GH_TOKEN: ${{ secrets.BOTTLE_ROCKET_REPO_PAT }}          