name: build-openapi

on:
  workflow_dispatch:
    
jobs:
  build-openapi-doc:
    runs-on: ubuntu-latest
    env:
      MAJOR_VERSION: 9
      MINOR_VERSION: 0
      SOLUTION_PATH: ./src/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x    
        
      - name: Restore dependencies
        run: dotnet restore $SOLUTION_PATH
      
      - name: Build
        run: dotnet build $SOLUTION_PATH --no-restore --ignore-failed-sources -c Release
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OPENAPI-JSON
          path: ./src/Rocket.Api.Host/openapi/Rocket.Api.Host.json
          if-no-files-found: error
          include-hidden-files: true
          
  update-openapi-doc:
    name: Commit API spec to document repo
    needs: build-openapi-doc
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: OPENAPI-JSON
          path: /home/runner/work/api-static/
          
      - name: Update version tag
        run: |
          cd /home/runner/work/api-static/
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "Version: $VERSION"
          sed -i "s/##{VERSION_TAG}##/$VERSION/g" Rocket.Api.Host.json
          
      - name: Set up Git Credentials
        run: git config --global url."https://x-access-token:${{ secrets.BOTTLE_ROCKET_REPO_PAT }}@github.com/".insteadOf "https://github.com/"              
          
      - name: Clone code, apply change, and push
        run : |
          cd /home/runner/work/          
          git clone https://github.com/gman-au/bottle-rocket-documentation.git api-docs
          cd api-docs
          git config user.name "Rocket-Bot"
          git config user.email "info@gman.com.au"
          git checkout -b api-version-${{ github.sha }}
          mv ../api-static/Rocket.Api.Host.json ./api-static/src/openapi/Rocket.Api.Host.json
          git add .          
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected. Preparing to commit and push."
            git commit -m "doc: Updated API document"
            git push --set-upstream origin api-version-${{ github.sha }}
          else
            echo "No changes to commit."
          fi          
          
      - name: Create Pull Request
        run: |
          cd api-docs
          gh pr create \
            --title "Update API documentation to ${{ github.ref_name }}" \
            --body "Automated update of OpenAPI specification" \
            --base main \
            --head "api-version-${{ github.sha }}"
        env:
          GH_TOKEN: ${{ secrets.BOTTLE_ROCKET_REPO_PAT }}          