name: build-openapi

on:
  push:
    branches: [ master ] 
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAJOR_VERSION: 9
      MINOR_VERSION: 0
      SOLUTION_PATH: ./src/
    - name: Checkout repository
      uses: actions/checkout@v4   
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x    
    - name: Add (ourCompliance) NuGet source
      run: dotnet nuget add source https://nuget.pkg.github.com/ourCompliance/index.json -u buildAgent -p ${{ secrets.OUR_PACKAGE_FEED_TOKEN }} --store-password-in-clear-text -n ourCompliance      
    - name: Add (G-MAN) NuGet source
      run: dotnet nuget add source https://nuget.pkg.github.com/gman-au/index.json -u buildAgent -p ${{ secrets.GMAN_PACKAGE_FEED_TOKEN }} --store-password-in-clear-text -n gmanau
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build $SOLUTION_PATH --no-restore --ignore-failed-sources -c Release
    - name: Test
      run: dotnet test $SOLUTION_PATH --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" || true
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: test
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true